FROM rust:1-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config libssl-dev libpq-dev python3 python3-pip libcairo2-dev \
    libpango1.0-dev python3-dev build-essential
RUN rm -rf /var/lib/apt/lists/*

RUN rustup component add clippy rustfmt

WORKDIR /src
EXPOSE 3060
CMD ["cargo", "run", "--bin", "backend"]
