FROM rust:1-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config libssl-dev libpq-dev
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /src
EXPOSE 3060
CMD ["cargo", "run", "--bin", "backend"]
