// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate serde;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum clz_Torappu_EPBreakBuffDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_EPBreakBuffData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_EPBreakBuffData<'a> {
    type Inner = clz_Torappu_EPBreakBuffData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> clz_Torappu_EPBreakBuffData<'a> {
    pub const VT_ELEMENTBREAKDURATION: flatbuffers::VOffsetT = 4;
    pub const VT_ELEMENTBUFFS: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_EPBreakBuffData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_EPBreakBuffDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_EPBreakBuffData<'bldr>> {
        let mut builder = clz_Torappu_EPBreakBuffDataBuilder::new(_fbb);
        if let Some(x) = args.elementBuffs {
            builder.add_elementBuffs(x);
        }
        builder.add_elementBreakDuration(args.elementBreakDuration);
        builder.finish()
    }

    pub fn unpack(&self) -> clz_Torappu_EPBreakBuffDataT {
        let elementBreakDuration = self.elementBreakDuration();
        let elementBuffs = self
            .elementBuffs()
            .map(|x| x.iter().map(|s| s.to_string()).collect());
        clz_Torappu_EPBreakBuffDataT {
            elementBreakDuration,
            elementBuffs,
        }
    }

    #[inline]
    pub fn elementBreakDuration(&self) -> f32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<f32>(
                    clz_Torappu_EPBreakBuffData::VT_ELEMENTBREAKDURATION,
                    Some(0.0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn elementBuffs(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>,
            >>(clz_Torappu_EPBreakBuffData::VT_ELEMENTBUFFS, None)
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_EPBreakBuffData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<f32>("elementBreakDuration", Self::VT_ELEMENTBREAKDURATION, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>,
            >>("elementBuffs", Self::VT_ELEMENTBUFFS, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_EPBreakBuffDataArgs<'a> {
    pub elementBreakDuration: f32,
    pub elementBuffs: Option<
        flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>,
    >,
}
impl<'a> Default for clz_Torappu_EPBreakBuffDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_EPBreakBuffDataArgs {
            elementBreakDuration: 0.0,
            elementBuffs: None,
        }
    }
}

pub struct clz_Torappu_EPBreakBuffDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> clz_Torappu_EPBreakBuffDataBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_elementBreakDuration(&mut self, elementBreakDuration: f32) {
        self.fbb_.push_slot::<f32>(
            clz_Torappu_EPBreakBuffData::VT_ELEMENTBREAKDURATION,
            elementBreakDuration,
            0.0,
        );
    }
    #[inline]
    pub fn add_elementBuffs(
        &mut self,
        elementBuffs: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<&'b str>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_EPBreakBuffData::VT_ELEMENTBUFFS,
            elementBuffs,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_EPBreakBuffDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_EPBreakBuffDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_EPBreakBuffData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_EPBreakBuffData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_EPBreakBuffData");
        ds.field("elementBreakDuration", &self.elementBreakDuration());
        ds.field("elementBuffs", &self.elementBuffs());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct clz_Torappu_EPBreakBuffDataT {
    pub elementBreakDuration: f32,
    pub elementBuffs: Option<Vec<String>>,
}
impl Default for clz_Torappu_EPBreakBuffDataT {
    fn default() -> Self {
        Self {
            elementBreakDuration: 0.0,
            elementBuffs: None,
        }
    }
}
impl clz_Torappu_EPBreakBuffDataT {
    pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_EPBreakBuffData<'b>> {
        let elementBreakDuration = self.elementBreakDuration;
        let elementBuffs = self.elementBuffs.as_ref().map(|x| {
            let w: Vec<_> = x.iter().map(|s| _fbb.create_string(s)).collect();
            _fbb.create_vector(&w)
        });
        clz_Torappu_EPBreakBuffData::create(
            _fbb,
            &clz_Torappu_EPBreakBuffDataArgs {
                elementBreakDuration,
                elementBuffs,
            },
        )
    }
}
pub enum dict__string__clz_Torappu_EPBreakBuffDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct dict__string__clz_Torappu_EPBreakBuffData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for dict__string__clz_Torappu_EPBreakBuffData<'a> {
    type Inner = dict__string__clz_Torappu_EPBreakBuffData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> dict__string__clz_Torappu_EPBreakBuffData<'a> {
    pub const VT_KEY: flatbuffers::VOffsetT = 4;
    pub const VT_VALUE: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        dict__string__clz_Torappu_EPBreakBuffData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args dict__string__clz_Torappu_EPBreakBuffDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<dict__string__clz_Torappu_EPBreakBuffData<'bldr>> {
        let mut builder = dict__string__clz_Torappu_EPBreakBuffDataBuilder::new(_fbb);
        if let Some(x) = args.value {
            builder.add_value(x);
        }
        if let Some(x) = args.key {
            builder.add_key(x);
        }
        builder.finish()
    }

    pub fn unpack(&self) -> dict__string__clz_Torappu_EPBreakBuffDataT {
        let key = {
            let x = self.key();
            x.to_string()
        };
        let value = self.value().map(|x| Box::new(x.unpack()));
        dict__string__clz_Torappu_EPBreakBuffDataT { key, value }
    }

    #[inline]
    pub fn key(&self) -> &'a str {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(
                    dict__string__clz_Torappu_EPBreakBuffData::VT_KEY,
                    None,
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn key_compare_less_than(&self, o: &dict__string__clz_Torappu_EPBreakBuffData) -> bool {
        self.key() < o.key()
    }

    #[inline]
    pub fn key_compare_with_value(&self, val: &str) -> ::core::cmp::Ordering {
        let key = self.key();
        key.cmp(val)
    }
    #[inline]
    pub fn value(&self) -> Option<clz_Torappu_EPBreakBuffData<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<clz_Torappu_EPBreakBuffData>>(
                    dict__string__clz_Torappu_EPBreakBuffData::VT_VALUE,
                    None,
                )
        }
    }
}

impl flatbuffers::Verifiable for dict__string__clz_Torappu_EPBreakBuffData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, true)?
            .visit_field::<flatbuffers::ForwardsUOffset<clz_Torappu_EPBreakBuffData>>(
                "value",
                Self::VT_VALUE,
                false,
            )?
            .finish();
        Ok(())
    }
}
pub struct dict__string__clz_Torappu_EPBreakBuffDataArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    pub value: Option<flatbuffers::WIPOffset<clz_Torappu_EPBreakBuffData<'a>>>,
}
impl<'a> Default for dict__string__clz_Torappu_EPBreakBuffDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        dict__string__clz_Torappu_EPBreakBuffDataArgs {
            key: None, // required field
            value: None,
        }
    }
}

pub struct dict__string__clz_Torappu_EPBreakBuffDataBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    dict__string__clz_Torappu_EPBreakBuffDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            dict__string__clz_Torappu_EPBreakBuffData::VT_KEY,
            key,
        );
    }
    #[inline]
    pub fn add_value(&mut self, value: flatbuffers::WIPOffset<clz_Torappu_EPBreakBuffData<'b>>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<clz_Torappu_EPBreakBuffData>>(
                dict__string__clz_Torappu_EPBreakBuffData::VT_VALUE,
                value,
            );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> dict__string__clz_Torappu_EPBreakBuffDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        dict__string__clz_Torappu_EPBreakBuffDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<dict__string__clz_Torappu_EPBreakBuffData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        self.fbb_
            .required(o, dict__string__clz_Torappu_EPBreakBuffData::VT_KEY, "key");
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for dict__string__clz_Torappu_EPBreakBuffData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("dict__string__clz_Torappu_EPBreakBuffData");
        ds.field("key", &self.key());
        ds.field("value", &self.value());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct dict__string__clz_Torappu_EPBreakBuffDataT {
    pub key: String,
    pub value: Option<Box<clz_Torappu_EPBreakBuffDataT>>,
}
impl Default for dict__string__clz_Torappu_EPBreakBuffDataT {
    fn default() -> Self {
        Self {
            key: "".to_string(),
            value: None,
        }
    }
}
impl dict__string__clz_Torappu_EPBreakBuffDataT {
    pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> flatbuffers::WIPOffset<dict__string__clz_Torappu_EPBreakBuffData<'b>> {
        let key = Some({
            let x = &self.key;
            _fbb.create_string(x)
        });
        let value = self.value.as_ref().map(|x| x.pack(_fbb));
        dict__string__clz_Torappu_EPBreakBuffData::create(
            _fbb,
            &dict__string__clz_Torappu_EPBreakBuffDataArgs { key, value },
        )
    }
}
pub enum clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a> {
    type Inner = clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a> {
    pub const VT_EP_BREAKBUFFS: flatbuffers::VOffsetT = 4;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'bldr>> {
        let mut builder = clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataBuilder::new(_fbb);
        if let Some(x) = args.ep_breakbuffs {
            builder.add_ep_breakbuffs(x);
        }
        builder.finish()
    }

    pub fn unpack(&self) -> clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataT {
        let ep_breakbuffs = self
            .ep_breakbuffs()
            .map(|x| x.iter().map(|t| t.unpack()).collect());
        clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataT { ep_breakbuffs }
    }

    #[inline]
    pub fn ep_breakbuffs(
        &self,
    ) -> Option<
        flatbuffers::Vector<
            'a,
            flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_EPBreakBuffData<'a>>,
        >,
    > {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    'a,
                    flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_EPBreakBuffData>,
                >,
            >>(
                clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData::VT_EP_BREAKBUFFS,
                None,
            )
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    '_,
                    flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_EPBreakBuffData>,
                >,
            >>("ep_breakbuffs", Self::VT_EP_BREAKBUFFS, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataArgs<'a> {
    pub ep_breakbuffs: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'a,
                flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_EPBreakBuffData<'a>>,
            >,
        >,
    >,
}
impl<'a> Default for clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataArgs {
            ep_breakbuffs: None,
        }
    }
}

pub struct clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_ep_breakbuffs(
        &mut self,
        ep_breakbuffs: flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'b,
                flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_EPBreakBuffData<'b>>,
            >,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData::VT_EP_BREAKBUFFS,
            ep_breakbuffs,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(
        self,
    ) -> flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData");
        ds.field("ep_breakbuffs", &self.ep_breakbuffs());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataT {
    pub ep_breakbuffs: Option<Vec<dict__string__clz_Torappu_EPBreakBuffDataT>>,
}
impl Default for clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataT {
    fn default() -> Self {
        Self {
            ep_breakbuffs: None,
        }
    }
}
impl clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataT {
    pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'b>> {
        let ep_breakbuffs = self.ep_breakbuffs.as_ref().map(|x| {
            let w: Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();
            _fbb.create_vector(&w)
        });
        clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData::create(
            _fbb,
            &clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffDataArgs { ep_breakbuffs },
        )
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_unchecked`.
pub fn root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data(
    buf: &[u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'_>, flatbuffers::InvalidFlatbuffer>
{
    flatbuffers::root::<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_unchecked`.
pub fn size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data(
    buf: &[u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'_>, flatbuffers::InvalidFlatbuffer>
{
    flatbuffers::size_prefixed_root::<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_unchecked`.
pub fn root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'b>, flatbuffers::InvalidFlatbuffer>
{
    flatbuffers::root_with_opts::<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'b>>(
        opts, buf,
    )
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_unchecked`.
pub fn size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_with_opts<
    'b,
    'o,
>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'b>, flatbuffers::InvalidFlatbuffer>
{
    flatbuffers::size_prefixed_root_with_opts::<
        clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'b>,
    >(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData`.
pub unsafe fn root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_unchecked(
    buf: &[u8],
) -> clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'_> {
    unsafe {
        flatbuffers::root_unchecked::<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData>(buf)
    }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData`.
pub unsafe fn size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_unchecked(
    buf: &[u8],
) -> clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'_> {
    unsafe {
        flatbuffers::size_prefixed_root_unchecked::<
            clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData,
        >(buf)
    }
}
#[inline]
pub fn finish_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_buffer<
    'a,
    'b,
    A: flatbuffers::Allocator + 'a,
>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_clz_torappu_simple_kvtable_clz_torappu_epbreak_buff_data_buffer<
    'a,
    'b,
    A: flatbuffers::Allocator + 'a,
>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_EPBreakBuffData<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
